theme: osuny-hugo-theme-aaa
paginate: 18
enableRobotsTXT: true
removePathAccents: true
params:
  plausible: francoisnemeta.fr
  logo:
    header: "/assets/images/logo.svg"
    footer: "/assets/images/logo.svg"
  breadcrumb:
    position: none
  summary:
    position: hero
  posts:
    date_format: "2006"